//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessions
    {
        public long UserId { get; set; }
        public string SessionKey { get; set; }
        public long IpAddress { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
